### ISSUE TITLE
UI kit

### ISSUE THREAD

**Issue by apetrikov** [kostrubin/fe_school_project#2]
Можно использовать уже готовые наборы компонентов и стилей. Это значительно ускорит процесс.

Например:
https://github.com/Semantic-UI-Vue/Semantic-UI-Vue
https://semantic-ui-vue.github.io/#/elements/input
https://vuetifyjs.com/ru/components/icons
https://vuematerial.io/

Мне семантик показался наиболее подходящим на первый взгляд.

**Comment by kostrubin** [comment]
Решил остановиться на Вьютифай
